name: Android Release

on:
  push
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'AdoptOpenJDK'
          java-version: "17.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true
      # next steps build the App for Android and Web. For further fluuter build configurations, check https://github.com/marketplace/actions/flutter-action
      - name: Get dependencies
        run: flutter pub get
      # - name: Run tests
      #   run: flutter test
      - name: Build Android APK
        run: flutter build apk
      - name: Build Android appbundle
        run: flutter build appbundle
      - name: Build Web
        run: flutter build web
